### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by jlag34** [mlrcbsousa/DesmotoArts#3]
Your files are coded really well. Both files include basically everything that is needed. In your HTML I'm glad you wrapped your segments with divs. In your CSS, nice job not repeating your styles. You indentation is perfect in both files as well. When I load the actual webpage, it looks just as it should. Really nice job on this project, keep up the great work!

**Comment by mlrcbsousa** [comment]
Thank you very much!
